In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, confusion_matrix
from sklearn import datasets

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.optimizers import Adam

In [2]:
# 데이터 불러오기
digits = datasets.load_digits()

digits

{'data': array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ..., 10.,  0.,  0.],
        [ 0.,  0.,  0., ..., 16.,  9.,  0.],
        ...,
        [ 0.,  0.,  1., ...,  6.,  0.,  0.],
        [ 0.,  0.,  2., ..., 12.,  0.,  0.],
        [ 0.,  0., 10., ..., 12.,  1.,  0.]]),
 'target': array([0, 1, 2, ..., 8, 9, 8]),
 'frame': None,
 'feature_names': ['pixel_0_0',
  'pixel_0_1',
  'pixel_0_2',
  'pixel_0_3',
  'pixel_0_4',
  'pixel_0_5',
  'pixel_0_6',
  'pixel_0_7',
  'pixel_1_0',
  'pixel_1_1',
  'pixel_1_2',
  'pixel_1_3',
  'pixel_1_4',
  'pixel_1_5',
  'pixel_1_6',
  'pixel_1_7',
  'pixel_2_0',
  'pixel_2_1',
  'pixel_2_2',
  'pixel_2_3',
  'pixel_2_4',
  'pixel_2_5',
  'pixel_2_6',
  'pixel_2_7',
  'pixel_3_0',
  'pixel_3_1',
  'pixel_3_2',
  'pixel_3_3',
  'pixel_3_4',
  'pixel_3_5',
  'pixel_3_6',
  'pixel_3_7',
  'pixel_4_0',
  'pixel_4_1',
  'pixel_4_2',
  'pixel_4_3',
  'pixel_4_4',
  'pixel_4_5',
  'pixel_4_6',
  'pixel_4_7',
  'pixel_5_0',
  'pixel_5_1',
 

In [3]:
X = digits.images

X

array([[[ 0.,  0.,  5., ...,  1.,  0.,  0.],
        [ 0.,  0., 13., ..., 15.,  5.,  0.],
        [ 0.,  3., 15., ..., 11.,  8.,  0.],
        ...,
        [ 0.,  4., 11., ..., 12.,  7.,  0.],
        [ 0.,  2., 14., ..., 12.,  0.,  0.],
        [ 0.,  0.,  6., ...,  0.,  0.,  0.]],

       [[ 0.,  0.,  0., ...,  5.,  0.,  0.],
        [ 0.,  0.,  0., ...,  9.,  0.,  0.],
        [ 0.,  0.,  3., ...,  6.,  0.,  0.],
        ...,
        [ 0.,  0.,  1., ...,  6.,  0.,  0.],
        [ 0.,  0.,  1., ...,  6.,  0.,  0.],
        [ 0.,  0.,  0., ..., 10.,  0.,  0.]],

       [[ 0.,  0.,  0., ..., 12.,  0.,  0.],
        [ 0.,  0.,  3., ..., 14.,  0.,  0.],
        [ 0.,  0.,  8., ..., 16.,  0.,  0.],
        ...,
        [ 0.,  9., 16., ...,  0.,  0.,  0.],
        [ 0.,  3., 13., ..., 11.,  5.,  0.],
        [ 0.,  0.,  0., ..., 16.,  9.,  0.]],

       ...,

       [[ 0.,  0.,  1., ...,  1.,  0.,  0.],
        [ 0.,  0., 13., ...,  2.,  1.,  0.],
        [ 0.,  0., 16., ..., 16.,  5.,  0.

In [4]:
y = digits.target

y

array([0, 1, 2, ..., 8, 9, 8])

In [5]:
X = digits.images.reshape(-1, 8, 8, 1)

X

array([[[[ 0.],
         [ 0.],
         [ 5.],
         ...,
         [ 1.],
         [ 0.],
         [ 0.]],

        [[ 0.],
         [ 0.],
         [13.],
         ...,
         [15.],
         [ 5.],
         [ 0.]],

        [[ 0.],
         [ 3.],
         [15.],
         ...,
         [11.],
         [ 8.],
         [ 0.]],

        ...,

        [[ 0.],
         [ 4.],
         [11.],
         ...,
         [12.],
         [ 7.],
         [ 0.]],

        [[ 0.],
         [ 2.],
         [14.],
         ...,
         [12.],
         [ 0.],
         [ 0.]],

        [[ 0.],
         [ 0.],
         [ 6.],
         ...,
         [ 0.],
         [ 0.],
         [ 0.]]],


       [[[ 0.],
         [ 0.],
         [ 0.],
         ...,
         [ 5.],
         [ 0.],
         [ 0.]],

        [[ 0.],
         [ 0.],
         [ 0.],
         ...,
         [ 9.],
         [ 0.],
         [ 0.]],

        [[ 0.],
         [ 0.],
         [ 3.],
         ...,
         [ 6.],
         [

In [6]:
# 데이터 정규화
scaler = StandardScaler()
X = scaler.fit_transform(X.reshape(-1, 64)).reshape(-1, 8, 8, 1)

# 원-핫 인코딩
Y = to_categorical(y)

In [7]:
X

array([[[[ 0.00000000e+00],
         [-3.35016487e-01],
         [-4.30810177e-02],
         ...,
         [-8.44129387e-01],
         [-4.09723921e-01],
         [-1.25022923e-01]],

        [[-5.90775571e-02],
         [-6.24009262e-01],
         [ 4.82974499e-01],
         ...,
         [ 1.12772113e+00],
         [ 8.79583060e-01],
         [-1.30433381e-01]],

        [[-4.46250733e-02],
         [ 1.11442724e-01],
         [ 8.95880438e-01],
         ...,
         [ 5.15471875e-01],
         [ 1.90596347e+00],
         [-1.14221844e-01]],

        ...,

        [[-6.13436689e-02],
         [ 8.10553603e-01],
         [ 6.30117142e-01],
         ...,
         [ 6.60964752e-01],
         [ 8.18450761e-01],
         [-8.87416172e-02]],

        [[-3.54332626e-02],
         [ 7.42118931e-01],
         [ 1.15065212e+00],
         ...,
         [ 5.37611162e-01],
         [-7.57435810e-01],
         [-2.09785127e-01]],

        [[-2.35964589e-02],
         [-2.99081347e-01],
         [

In [8]:
Y

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 1., 0.]])

In [9]:
# 훈련, 테스트 데이터 분할
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=0)

# 훈련, 테스트 데이터 형태 확인
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((1437, 8, 8, 1), (360, 8, 8, 1), (1437, 10), (360, 10))

In [10]:
# CNN 모델 정의
model = Sequential()

# 첫 번째 Conv2D 레이어
model.add(Conv2D(32, (2, 2), activation='relu', input_shape=(8, 8, 1)))
model.add(MaxPooling2D(pool_size=(2, 2)))

# 두 번째 Conv2D 레이어
model.add(Conv2D(64, (2, 2), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

# Flatten 레이어
model.add(Flatten())

# Fully Connected Layer
model.add(Dense(64, activation='relu'))

# 출력층
model.add(Dense(10, activation='softmax'))

# 모델 컴파일
model.compile(optimizer=Adam(learning_rate=0.001), 
              loss='categorical_crossentropy', 
              metrics=['accuracy'])

# 모델 요약
model.summary()

c:\Users\tjdgu\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv2d (Conv2D)                 │ (None, 7, 7, 32)       │           160 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d (MaxPooling2D)    │ (None, 3, 3, 32)       │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_1 (Conv2D)               │ (None, 2, 2, 64)       │         8,256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_1 (MaxPooling2D)  │ (None, 1, 1, 64)       │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten (Flatten)               │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 64)             │         4,160 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 10)             │           650 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 13,226 (51.66 KB)

 Trainable params: 13,226 (51.66 KB)

 Non-trainable params: 0 (0.00 B)

In [11]:
# 모델 학습
model_history = model.fit(X_train, y_train, epochs=30, batch_size=32, validation_data=(X_test, y_test))

Epoch 1/30
45/45 ━━━━━━━━━━━━━━━━━━━━ 4s 21ms/step - accuracy: 0.2094 - loss: 2.1929 - val_accuracy: 0.4750 - val_loss: 1.7814
Epoch 2/30
45/45 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - accuracy: 0.6411 - loss: 1.4916 - val_accuracy: 0.6972 - val_loss: 1.0449
Epoch 3/30
45/45 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - accuracy: 0.8082 - loss: 0.7810 - val_accuracy: 0.8167 - val_loss: 0.7091
Epoch 4/30
45/45 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - accuracy: 0.8871 - loss: 0.4952 - val_accuracy: 0.8472 - val_loss: 0.5536
Epoch 5/30
45/45 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - accuracy: 0.9035 - loss: 0.3702 - val_accuracy: 0.8778 - val_loss: 0.4444
Epoch 6/30
45/45 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - accuracy: 0.9408 - loss: 0.2552 - val_accuracy: 0.9000 - val_loss: 0.4064
Epoch 7/30
45/45 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - accuracy: 0.9455 - loss: 0.1918 - val_accuracy: 0.9056 - val_loss: 0.3525
Epoch 8/30
45/45 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - accuracy: 0.9662 - loss: 0.1616 - val_accuracy: 0.9000 - v

In [12]:
# 평가
loss, accuracy = model.evaluate(X_test, y_test)
print(f"Test Loss: {loss:.4f}, Test Accuracy: {accuracy:.4f}")

12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9554 - loss: 0.1540
Test Loss: 0.2534, Test Accuracy: 0.9556
